### ISSUE TITLE
请问可以试试Gitlab吗？也许可以解决mp3上传问题

### ISSUE THREAD

**Issue by worx7kbj** [Editst/LoudMurmurs#1]

**Comment by Editst** [comment]
主要是 GitHub 限制了单个文件最大为 100M，否则要使用 git lfs，现在懒得搞，之后再看看

**Comment by worx7kbj** [comment]
我记得gitlab限制大一点

**Comment by Editst** [comment]
没具体测试，如果确实需要的话可以按照 README 中给出的链接下载，里面是所有音频文件的地址
