### ISSUE TITLE
小声喧哗博主不是很希望在网上有可以直接获取的备份，感觉是不是不上传mp3会比较好

### ISSUE THREAD

**Issue by Yiyiyimu** [Editst/LoudMurmurs#2]

**Comment by Editst** [comment]
目前也没有上传 mp3 文件，只是备份了网站的文字内容

**Comment by shuyaoli** [comment]
根据她们的网站（比如[这个](https://loudmurmursfm.com/episodes/s4-e28-2021yearend)），音频是liscenced under Creative Commons Attribution 4.0 International，所以…

**Comment by Yiyiyimu** [comment]
> 根据她们的网站（比如[这个](https://loudmurmursfm.com/episodes/s4-e28-2021yearend)），音频是liscenced under Creative Commons Attribution 4.0 International，所以…

嗯但现在不是情况比较特殊。。虽然是 CC 但还是尊重作者意愿比较好

**Comment by Yiyiyimu** [comment]
> 目前也没有上传 mp3 文件，只是备份了网站的文字内容

看到更新的 REAME 了，多谢多谢！
